name-template: 'v${{ version }}'
tag-template: 'v${{ version }}'

categories:
  - title: 'Bug Fixes'
    label: 'fix'
  - title: 'Features'
    label: 'feat'
  - title: 'Other'
    label: 'chore'
    label: 'docs'

change-template: '- ${{ issue.title }} (#${{ issue.number }})'
